### ISSUE TITLE
How can I install it on Windows?

### ISSUE THREAD

**Issue by alexchern** [zhm/node-spatialite#9]
Hi there,

I could not install it on Windows.
![npmlog](https://cloud.githubusercontent.com/assets/9559649/6504912/0659512e-c345-11e4-94b8-1a4624eb438c.png)

What did I do wrong?

Thanks,

Alex

**Comment by zachatrocity** [comment]
1. Install Python 2.7
2. Set your [python environment variable](https://docs.python.org/2/using/windows.html#excursus-setting-environment-variables)

**Comment by zhm** [comment]
The shortcomings of getting this working on Windows are known. I don't use Windows and don't have a ton of time to devote to making it work. I would gladly accept any changes that improve Windows compatibility.
